import Head from "next/head";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import PokemonListContainer from "../container/PokemonListContainer";
import styled from "@emotion/styled";
import Layout from "../container/Layout";
import Header from "../components/Header";
import MainContainer from "../container/MainContainer";
import FixedMainContainer from "../container/FixedMainContainer";
import { useQuery } from "@apollo/client";
import { GET_POKEMONS } from "../graphql/apis";
import { useAppContext } from "../context/state";
import { initializeApollo } from "../lib/apolloClient";
import { extractNumber } from "../lib/helpers/stringHelper";
import LoadMore from "../components/LoadMore";
import Button from "../components/Button";

export default function Home(props) {
    // saving state immediately because props.data already exist (caused by SSR)
    const state = useAppContext();

    const [tdata, setTData] = useState(props.data);
    const [next, setNext] = useState(props.data.pokemons.results.length);
    const [isLoadingMore, setIsLoadingMore] = useState(false);

    const { loading, error, data, fetchMore } = useQuery(GET_POKEMONS, {
        variables: {
            limit: 10,
            offset: next,
        },
    });

    useEffect(() => {
        if (!isLoadingMore && data) {
            const currentPokemons = state.pokemons;
            const newPokemons = data.pokemons.results;
            const allPokemons = currentPokemons.concat(newPokemons);
            state.setPokemons(allPokemons);
            setNext(allPokemons.length);
        }
    }, [isLoadingMore]);

    const onClickLoadMore = async () => {
        setIsLoadingMore(true);
        await fetchMore({
            variables: {
                // limit: data.launches.cursor,
                limit: 10,
                offset: 9,
            },
        });

        setIsLoadingMore(false);
    };

    useEffect(() => {
        state.setPokemons(props.data.pokemons.results);
        setTData(props.data);
    }, []);

    // console.log(props.data, data);

    // useEffect(() => {
    //     if (data) state.setPokemons(data.pokemons.results);
    // }, [data]);
    return (
        <Layout>
            <Head>
                <title>Pokedex</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <MainContainer>
                <FixedMainContainer>
                    <PokemonListContainer data={{ pokemons: { results: state.pokemons } }} />
                    <div style={{ display: "flex", justifyContent: "center", margin: "10px 0" }}>
                        {/* <Button onClick={onClickLoadMore}>Load more</Button> */}
                        {props.data && <Button onClick={onClickLoadMore}>Load more</Button>}
                    </div>
                </FixedMainContainer>
            </MainContainer>
        </Layout>
    );
}

export async function getServerSideProps() {
    const apolloClient = initializeApollo();

    const res = await apolloClient.query({
        query: GET_POKEMONS,
        variables: {
            limit: 10,
            offset: 0,
        },
    });

    return {
        props: {
            // data: apolloClient.cache.extract(),
            data: res.data,
        },
    };
}
